config/routes.rb
Rr::Application.routes.draw do
  resources :authors

root to: 'articles#index'
 get "tags/index"

  get "tags/show"
  get "articles/about_us"
  get "articles/contact_us"
  get "articles/blogger_information"
  get "articles/me_us"
  
  match 'login'  => 'author_sessions#new',     as: :login
  match 'logout' => 'author_sessions#destroy', as: :logout

  resources :author_sessions


  resources :comments
    resources :articles

    resources :tags




end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image

attr_accessible :image 
attr_accessible :title, :body, :tag_list, :image

 def tag_list
    return self.tags.join(", ")
  end
  def tag_list
  self.tags.collect do |tag|
    tag.name
  end.join(", ")
 end
def to_s
    name
  end
    def tag_list=(tags_string)
    self.taggings.destroy_all

    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq

    tag_names.each do |tag_name|
      tag = Tag.find_or_create_by_name(tag_name)
      tagging = self.taggings.new
      tagging.tag_id = tag.id
    end

end
end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
    validates_confirmation_of :password, message: "should match confirmation", if: :password

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	# allow for mass assignment
attr_accessible :author_name, :body
belongs_to :article   
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	 has_many :taggings
  has_many :articles, through: :taggings
has_many :taggings, dependent: :destroy
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :article
  belongs_to :tag
tags = article.taggings.collect{|tagging| tagging.tag}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	

	def index
		@articles = Article.all
end
def show
@article = Article.find(params[:id])
@comment = Comment.new
@comment.article_id = @article.id

	end

	def new
@article = Article.new

	end
	def create
  @articles = Article.new(params[:article])
    @articles.save
redirect_to article_path(@articles)
flash[:notice] ="Article Created"

	end
	def edit
		@articles = Article.find(params[:id])

	end
	
	before_filter :require_login, only: [:update]
	def update
    @articles = Article.find(params[:id])
    @articles.update_attributes(params[:article])
flash[:notice] = "Article '#{@articles.title}' Updated!"
    redirect_to article_path(@article)
  end

before_filter :require_login, only: [:destroy]
def destroy
  @articles=Article.find(params[:id])
		if @articles.delete
			flash[:notice]="Hurrey! your comment is deleted"
			redirect_to :action=>'index'
	else
		render 'index'
	end
end
def about_us
	end
	def contact_us
	end
	def blogger_information
	end
def me_us
	
end

end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController

def new
    @author = Author.new
  end

  def create
    if @author == login(params[:username], params[:password])
      redirect_back_or_to(articles_path, messages: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, message: 'Logged out!')
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

before_filter :require_login, except: [:new, :create]
before_filter :zero_authors_or_authenticated, only: [:new, :create]

 
  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end


  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

before_filter :require_login, except: [:new, :create]
  before_filter :zero_authors_or_authenticated, only: [:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end


  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :ok }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_filter :require_login, except: [:create]
def create
	article_id = params[:comment].delete(:article_id)

  @comment = Comment.new(params[:comment])
  @comment.article_id = article_id
    @comment.save
redirect_to article_path(@comment.article)
flash[:notice] = "Comment is posted"
end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  	@tag = Tag.all

end


  def show
  	@tag = Tag.find(params[:id])
  	
  end
before_filter :require_login, only: [:destroy]
def destroy
  @tag=Tag.find(params[:id])
		if @tag.delete
			flash[:notice]="Hurrey! your comment is deleted"
			redirect_to :action=>'index'
	else
		render 'index'
	end

 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def tag_links(tags)
    links = tags.collect{|tag| link_to tag.name, tag_path(tag)}
    return links.join(", ").html_safe
  end

	  

end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
	 @tag = Tag.all
end

app/views/articles/_comment.html.erb

 <div class="comment">
  <u><li><h4><p style="color:blue">Comment by <%= comment.author_name %></h4></li></u>
  <p style="color:green"><%= comment.body %></p>
<p style="color:black">Posted 
	<%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later

<%= Time.now.strftime("%m/%d/%Y") %> </p>



</div>

app/views/articles/_comment_form.html.erb
<u><h3 style="color:blue">Post a  New Comment</h3></u>
<%= form_for @comment do |f| %>
  <%= f.hidden_field :article_id %>
  <p>
    <%= f.label :author_name,"Your Name" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Body" %><br/>
    <%= f.text_field :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@articles, html: {multipart: true}) do |f| %>

	<ul>
		<% @articles.errors.full_messages.each do |error| %>
		<li><%= erroe %></li>
		<% end %>
	</ul>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :body %><br />
		<%= f.text_area :body %>
	</p>
	 <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
   <p>
     <p>
    <%= f.label :image, "Attach an Image" %><br />
    <%= f.file_field :image %>
  </p>

	<p>
		<%= f.submit "save" %>
	</p>
	
	<% end %>



app/views/articles/about_us.html.erb
<h2><i><u>About us</u></i></h2> 
	
	<h3><u><i><font color="blue">The Story of Blogger:-</font></i></u></h3><br/>
	
<p><font color="black">
Blogger was started by a tiny project started in small company called Gowdanar Technology in August of 2012. This was in the midst of the unemployment and recession. But we were not exactly a VC-funded, party-throwing, football-in-the-lobby-playing, free-beer-drinking outfit. (Unless it was other people's free beer.)

We were three friends, funded by doing annoying contract web projects for big companies, trying to make our own grand entrance onto the Internet landscape. What we were originally trying to do does not matter so much now. But while doing it, we created Blogger, more or less on a whim and thought — Hmmm...this is interesting.


Things are going well. We have handful of users, though still just a few people. 

We like Google a lot. And their blogs. So we liked the idea of creating a blog. And hope it works out nicely.</font></p><br/><br/>
<br/>
<br/>

<br/>
<br/>

<br/>
<br/>
<br/>
<br/>

<%= link_to 'Home',{:action=>'index', :controller=>'articles'}%>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
<%= link_to "New Article", new_article_path, :class => "new_article" %>
<%= link_to 'Blogger Information', :action=>'blogger_information'%>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
<%= link_to 'Dominus', :action=>'me_us'%>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp

<%= link_to 'Contact us', :action=>'contact_us'%>


app/views/articles/contact_us.html.erb
<h2><u>Contact us</u></h2>


<ol>


   <p><b><font color="blue">Blogger Developer:-</font></b></u></p>
  <h1> <p><b><font color="blue">Rakesh Kumar:-</font></b></p></h1>
   <p><font color="blue">Email id :-<font color="black" >rakeshmaurya262@gmail.com,<br/> 
                                         sunnymaurya262@yahoo.com<br/>

   <p><font color="blue">Permanent Address :- <font color="black"> Vill-Bhagchuri<br/>
   	Po-Nausar<br/>
   	Udham Singh Nagar<br/>
   	Pin-262308<br/>
   	Uttarakhand
   	India</font></p>
   	<p><font color="">Current Address :-<font color="black"> Cauvery Boys Hostel<br/>
   	CQAL Layout<br/>
   	SahakaraNagar<br/>
   	Bangalore-560092<br/>
   	Karnataka
   	India</font>
   	<br/>
<br/>

<br/>
<br/>

<br/>
<br/>




</ol>
<%= link_to 'Home',{:action=>'index', :controller=>'articles'}%>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
<%= link_to " Create New Article", new_article_path, :class => "new_article" %>
<%= link_to 'Blogger Information', :action=>'blogger_information'%>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
<%= link_to 'Dominus', :action=>'me_us'%>


app/views/articles/edit.html.erb

<h1 style="color:black";>Edit an Article</h1>

<%= render :partial => 'form' %>

</p>
<%= link_to "back to articles" , articles_path %>
</p>

app/views/articles/index.html.erb






<h2>
<body>
<div id="topbar">
<ul id="topnav">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp

  <a href="/articles/about_us">About us</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp   
  <a href="/articles/me_us">Dominus</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp   
  <a href="/articles/contact_us">Contact us</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp   
  <a href="/articles/blogger_information">Blogger Information</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp 
  <br/>
  <br/>
</body>
</h2>



<h2>All Articles</h2>

<ul>
<% @articles.each do |article| %>
<li>
<%= link_to article.title, article_path(article) %>

</li>
<% end %>
</ul>

<br>
<h3>
	
<%= link_to "Create a New Article", new_article_path, class: "new_article" %>
</br>
<br>
<div id="footer" style="background-color:#FFA500;clear:both;text-align:center;">

Copyright:- rakeshmaurya262@gmail.com</div>
<br/>








app/views/articles/me_us.html.erb
<h3><i><u>About the Developer :- </i></u></h3>
<%= image_tag("rakesh1.jpg", :alt => "rakesh") %>

   <p><font color="blue">Email id :-<font color="black"> rakeshmaurya262@gmail.com</font>
<p><font color="blue" >Website :-<font color="black"> https://www.facebook.com/rakeshmaurya262</font>
</p>
   <p><font color="black">
I am Rakesh Kumar . <br/>
Currently working as a Trainee developer and chasing my dream to work in an MNC.
<br/>
<p><font color="blue">Qualifications:-  <font color="black">Bachelors In Engineering(Computer Science)<br/>
Working as Trainee Developer@ Gowdanar Technologies<br/>
 <font color="blue">Date of birth :-<font color="black"> 05/06/1990
<p><font color="blue">Mobile Number :-<font color="black"> +91-7204189255</font></p>
</font></p>
</font></p><br/><br/>

<%= link_to "Create new Article", new_article_path, :class => "new_article" %>
<%= link_to "Home", articles_path, :class=>"articles"%>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp   

<%= link_to 'contact us', :action=>'contact_us'%>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
<%= link_to 'Blogger Information', :action=>'blogger_information'%>

app/views/articles/new.html.erb
<h1> Create a New Article </h1>
<%= form_for(@article) do |f| %>
	<ul>
		<% @article.errors.full_messages.each do |error| %>
		<li><%= erroe %></li>
		<% end %>
	</ul>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :body %><br />
		<%= f.text_area :body %>
	</p>
	  <p>
    <%= f.label :image, "Attach an Image" %><br />
    <%= f.file_field :image %>
  </p>

	<p>
		<%= f.submit %>
	</p>
	<%= link_to "Back to All Articles" , articles_path %>
	<% end %>

app/views/articles/show.html.erb
<% if logged_in? %>

<h1><%= @article.title %></h1>
<b><p style="color:blue">Tags: <%= tag_links(@article.tags) %></p></b>
	
<p style="color:black"><%= image_tag @article.image.url %></p>

<p style="color:black"><%= @article.body %></p>

<h2><p style="color:blue">Comments(<%= @article.comments.count %>)</h2>
<%= render partial: 'comment', collection: @article.comments %>

<%= link_to "Delete", article_path(@article), method: :delete, :confirm => "Really delete the article?" %>

<p><%= link_to "Edit" , edit_article_path(@articles) %></h3>

</p>

<%= render partial: 'comment_form' %>
<%= link_to "back to the Articles" , articles_path %>
</p>
	
<% end %> 

app/views/author_sessions/new.html.haml

%h2 Login

= form_tag author_sessions_path, method: :post do
  .field
    = label_tag :username
    = text_field_tag :username
    %br/
  .field
    = label_tag :password
    = password_field_tag :password
    %br/
  .actions
    = submit_tag "Login"

= link_to 'Back to Articles', articles_path
%h4 Default User-name  admin
%h4 Default Password is admin

app/views/authors/_form.html.haml
= form_for @author do |f|
  - if @author.errors.any?
    #error_explanation
      %h2= "#{pluralize(@author.errors.count, "error")} prohibited this author from being saved:"
      %ul
        - @author.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.text_field :password
  .field
    = f.label :password_confirmation
    = f.text_field :password_confirmation
  .actions
    = f.submit 'Save'

app/views/authors/edit.html.haml
%h1 Editing author

= render 'form'

= link_to 'Show', @author 
= link_to 'Back', authors_path 

app/views/authors/index.html.haml
%h1 Listing authors

%table
  %tr
    %th Username
    %th Email
    %th Crypted password
    %th Salt
    %th
    %th
    %th

  - @authors.each do |author|
    %tr
      %td= author.username
      %td= author.email
      %td= author.crypted_password
      %td= author.salt
      %td= link_to 'Show', author
      %td= link_to 'Edit', edit_author_path(author)
      
     

%br

= link_to 'New Author', new_author_path
= link_to 'Back to Home', articles_path

app/views/authors/new.html.haml
%h1 New author

= render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.haml
%p #notice= notice

%p
  %b Username:
  = @author.username
%p
  %b Email:
  = @author.email
%p
  %b Crypted password:
  = @author.crypted_password
%p
  %b Salt:
  = @author.salt

= link_to 'Edit', edit_author_path(@author)
= link_to 'Back', authors_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blogger
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %body
    #container
      #content
        = yield
        %hr
        %h6
          - if logged_in?
            = "Logged in as #{current_user.username}"
            = link_to "(logout)", logout_path
          - else
            = link_to "(login)", login_path

app/views/tags/index.html.erb
<h1>Tags#index</h1>
<h1>hello</h1>
	
	

app/views/tags/show.html.erb
<h1 style="color:blue">Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>